spring.application.name=user-service
server.port=${user-service.uriport}

spring.cloud.config.profile=dev
spring.config.import=optional:configserver:http://localhost:8888

spring.datasource.url=${user-service.datasource-url}
spring.jpa.defer-datasource-initialization=true
spring.datasource.username=${user-service.username}
spring.datasource.password=${user-service.password}

spring.jpa.hibernate.ddl-auto=${user-service.hibernate-ddl-auto}
spring.jpa.show-sql=${user-service.showsql}
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

eureka.client.service-url.defaultZone: ${user-service.urlregistry}

eureka.instance.prefer-ip-address=true
eureka.instance.instance-id=${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}